#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────
# configure_android.sh — single source of truth for the Android Firebase /
# build config, applied AFTER `flutter create --platforms=android .`.
#
# Because android/ is git-ignored and regenerated by CI, this script re-applies
# everything a fresh generation drops:
#   1. applicationId = com.hoberadius.app   (must match google-services.json)
#   2. android/app/google-services.json     (copied from tool/firebase/)
#   3. the com.google.gms.google-services Gradle plugin (project + app level,
#      Kotlin-DSL and Groovy both handled)
#   4. INTERNET permission + cleartext traffic in the release manifest
#
# Idempotent: safe to run repeatedly. Wire into CI right after `flutter create`.
# ─────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_ID="com.hoberadius.app"
GS_VERSION="4.4.2"

[ -d "$ROOT/android" ] || { echo "::error:: android/ not found — run 'flutter create --platforms=android .' first"; exit 1; }

# 1) google-services.json ----------------------------------------------------
mkdir -p "$ROOT/android/app"
cp "$ROOT/tool/firebase/google-services.json" "$ROOT/android/app/google-services.json"
echo "✓ placed android/app/google-services.json"

# 2) applicationId -----------------------------------------------------------
patch_app_id() {
  local f="$1"
  [ -f "$f" ] || return 0
  if grep -qE 'applicationId\s*=\s*"' "$f"; then          # Kotlin DSL
    sed -i -E "s|applicationId\s*=\s*\"[^\"]*\"|applicationId = \"$APP_ID\"|" "$f"
  elif grep -qE 'applicationId\s+"' "$f"; then            # Groovy
    sed -i -E "s|applicationId\s+\"[^\"]*\"|applicationId \"$APP_ID\"|" "$f"
  fi
  echo "✓ applicationId set in $(basename "$f"): $(grep -oE 'applicationId[^0-9A-Za-z]*"[^"]*"' "$f" | head -1)"
}
patch_app_id "$ROOT/android/app/build.gradle.kts"
patch_app_id "$ROOT/android/app/build.gradle"

# 2b) core library desugaring (required by flutter_local_notifications) -------
DESUGAR_VER="2.1.4"
patch_desugar() {
  local f="$1" kotlin="$2"
  [ -f "$f" ] || return 0
  # enable the flag inside compileOptions
  if ! grep -q 'isCoreLibraryDesugaringEnabled\|coreLibraryDesugaringEnabled' "$f"; then
    if [ "$kotlin" = "1" ]; then
      sed -i -E '/compileOptions \{/a\        isCoreLibraryDesugaringEnabled = true' "$f"
    else
      sed -i -E '/compileOptions \{/a\        coreLibraryDesugaringEnabled true' "$f"
    fi
  fi
  # add the desugar dependency (a second dependencies{} block is valid Gradle)
  if ! grep -q 'desugar_jdk_libs' "$f"; then
    if [ "$kotlin" = "1" ]; then
      printf '\ndependencies {\n    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:%s")\n}\n' "$DESUGAR_VER" >> "$f"
    else
      printf "\ndependencies {\n    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:%s'\n}\n" "$DESUGAR_VER" >> "$f"
    fi
  fi
  echo "✓ core library desugaring enabled in $(basename "$f")"
}
patch_desugar "$ROOT/android/app/build.gradle.kts" 1
patch_desugar "$ROOT/android/app/build.gradle" 0

# 3) google-services Gradle plugin ------------------------------------------
# Kotlin DSL (modern Flutter): declarative plugins{} in settings + app.
SETTINGS_KTS="$ROOT/android/settings.gradle.kts"
APP_KTS="$ROOT/android/app/build.gradle.kts"
SETTINGS_GROOVY="$ROOT/android/settings.gradle"
PROJ_GROOVY="$ROOT/android/build.gradle"
APP_GROOVY="$ROOT/android/app/build.gradle"

if [ -f "$SETTINGS_KTS" ] && [ -f "$APP_KTS" ]; then
  if ! grep -q 'com.google.gms.google-services' "$SETTINGS_KTS"; then
    # insert after the com.android.application plugin line (has `apply false`)
    sed -i -E "/id\(\"com\.android\.application\"\).*apply false/a\\    id(\"com.google.gms.google-services\") version \"$GS_VERSION\" apply false" "$SETTINGS_KTS"
    echo "✓ google-services declared in settings.gradle.kts"
  fi
  if ! grep -q 'com.google.gms.google-services' "$APP_KTS"; then
    sed -i -E "/id\(\"com\.android\.application\"\)/a\\    id(\"com.google.gms.google-services\")" "$APP_KTS"
    echo "✓ google-services applied in app/build.gradle.kts"
  fi
elif [ -f "$APP_GROOVY" ]; then
  # Groovy fallback.
  if [ -f "$SETTINGS_GROOVY" ] && grep -q 'com.android.application' "$SETTINGS_GROOVY" && ! grep -q 'com.google.gms.google-services' "$SETTINGS_GROOVY"; then
    sed -i -E "/id 'com\.android\.application'.*apply false/a\\    id 'com.google.gms.google-services' version '$GS_VERSION' apply false" "$SETTINGS_GROOVY"
    echo "✓ google-services declared in settings.gradle"
  elif [ -f "$PROJ_GROOVY" ] && ! grep -q 'com.google.gms:google-services' "$PROJ_GROOVY"; then
    sed -i -E "s|(dependencies\s*\{)|\1\n        classpath 'com.google.gms:google-services:$GS_VERSION'|" "$PROJ_GROOVY"
    echo "✓ google-services classpath added to build.gradle"
  fi
  if ! grep -q 'com.google.gms.google-services' "$APP_GROOVY"; then
    printf "\napply plugin: 'com.google.gms.google-services'\n" >> "$APP_GROOVY"
    echo "✓ google-services applied in app/build.gradle"
  fi
fi

# 4) INTERNET permission + cleartext (owner server is http://) ---------------
MF="$ROOT/android/app/src/main/AndroidManifest.xml"
if [ -f "$MF" ]; then
  if ! grep -q 'android.permission.INTERNET' "$MF"; then
    sed -i -E '0,/<manifest[^>]*>/s##&\n    <uses-permission android:name="android.permission.INTERNET"/>#' "$MF"
    echo "✓ INTERNET permission added"
  fi
  if ! grep -q 'usesCleartextTraffic' "$MF"; then
    sed -i -E '0,/<application/s##<application android:usesCleartextTraffic="true"#' "$MF"
    echo "✓ usesCleartextTraffic=true added"
  fi
fi

echo "✓ configure_android.sh complete"
